[colors.primary]
background = '#131315'
foreground = '#e4e2e3'

[colors.selection]
text = '#e4e2e3'
background = '#414753'

[colors.cursor]
text = '#131315'
cursor = '#c1c6d6'

[colors.normal]
black   = '#131315'
red     = '#f66e93'
green   = '#6bd67b'
yellow  = '#fff872'
blue    = '#b3b9cb'
magenta = '#515563'
cyan    = '#c1c6d6'
white   = '#d3d6e0'

[colors.bright]
black   = '#80828b'
red     = '#ff9fb9'
green   = '#a5ffb3'
yellow  = '#fffba5'
blue    = '#d7dceb'
magenta = '#edf1ff'
cyan    = '#f3f6ff'
white   = '#f8faff'
