cursor #e4e2e2
cursor_text_color #c4c7cb

foreground            #e4e2e2
background            #131314
selection_foreground  #2d3134
selection_background  #c4c7cb
url_color             #bdc8d2

color0   #131314
color1   #e64c48
color2   #72d66e
color3   #dbd07b
color4   #5a85b6
color5   #90979d
color6   #bdc8d2
color7   #abb2bf
color8   #5c6370
color9   #e05f60
color10  #88e086
color11  #e8df97
color12  #cad6e1
color13  #4e7f99
color14  #657aa0
color15  #ffffff
